name: release

on:
  # Run when a new tag is pushed
  push:
    tags:
      - 'v*.*.*'

permissions:
  attestations: write
  contents: write
  id-token: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Clone code
        uses: actions/checkout@v4

      - name: Zip assets
        run: |
          zip -r student-env.zip .devcontainer scripts README.md

      - name: Add the zip to the release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          files: student-env.zip

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Generate Docker metadata
        id: docker_metadata
        uses: docker/metadata-action@v5
        with:
          flavor: latest=true
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=sha

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .devcontainer
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Attest and push Docker image
        uses: actions/attest-build-provenance@v2
        id: attest
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
