name: release

on:
  # Run when a new tag is pushed
  push:
    tags:
      - 'v*.*.*'

  # Run when manually triggered
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v4

      - name: Zip assets
        run: |
          zip -r student-env.zip .devcontainer scripts README.md

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          files: student-env.zip